For 2 arryas, finding common elements

In [1]:
import numpy as np
a =np.array([1,2,3,2,3,4,3,4,5,6])
b =np.array([7,2,10,2,7,4,9,4,9,8])
c =np.intersect1d(a,b)
print(c)

[2 4]

For 2 or more arrays, finding commom elements

In [2]:
a =np.array([1,2,3,2,3,4,3,10,2,74,5,6])
b =np.array([7,2,10,2,7,4,9,4,9,8])
c =np.array([10,2,7,4,9])
from functools import reduce
reduce(np.intersect1d, (a,b,c))

array([ 2,  4, 10])

In [3]:
def start_end(arr,st,end):
    return arr[(arr>st)&(arr<end)]
start_end(a,3,10)

array([4, 5, 6])

In [4]:
# Understand where properly before seeing this and boolean array indexing
np.random.seed(35265) # Used to maintain RandomState
A = np.random.randint(1, 100, (7, 5))
#print(A,"\n")
''' A[:,1]>50 checks elements which are greater than 50 for all rows in 2nd column, returns the result in array when we use 
    np.where '''
print(np.where(A[:,2]>50))
''' A[np.where(A[:,1]>50),1] displays the elements which are greater than 50 in 2nd column '''
print(A[np.where(A[:,2]>50),2])
print(A[np.where(A[:,4]%2==1),4])

(array([0, 4, 6], dtype=int32),)
[[75 57 72]]
[[ 7 51 67 41]]

In [5]:
A.max(axis=0)
A

array([[81,  8, 75, 85,  7],
       [58, 22, 22, 10, 48],
       [86, 56, 29, 25, 51],
       [71, 62, 33, 48, 82],
       [51, 22, 57, 57, 67],
       [65, 49, 19, 73, 41],
       [97, 39, 72, 14, 50]])

In [6]:
#Indexes of the maximal elements of a N-dimensional array:
ind = np.unravel_index(np.argmax(A, axis=0), a.shape)
ind

(array([6, 3, 0, 0, 3], dtype=int32),)

In [7]:
A[ind,:] = 0
A.max(axis=0) # Second highest element

array([86, 56, 57, 73, 67])

In [8]:
def close(arr,x):
    ar = arr - x
    ar = np.absolute(ar)
    return arr[(np.unravel_index(np.argmin(ar, axis=None), ar.shape))]
    # (or) arr[np.where(ar == ar.min())]
print(b)
print(close(b,6))

[ 7  2 10  2  7  4  9  4  9  8]
7

# Pandas

In [9]:
import pandas as pd

In [11]:
data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",delimiter="|")
data

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
5          6   42      M      executive    98101
6          7   57      M  administrator    91344
7          8   36      M  administrator    05201
8          9   29      M        student    01002
9         10   53      M         lawyer    90703
10        11   39      F          other    30329
11        12   28      F          other    06405
12        13   47      M       educator    29206
13        14   45      M      scientist    55106
14        15   49      F       educator    97301
15        16   21      M  entertainment    10309
16        17   30      M     programmer    06355
17        18   35      F          other    37212
18        19   40      M      librarian    02138
19        20   42      F      homemaker    95660
20        21   26      M         writer    30068
21        22   25      M         writer    40206
22        23   30      F         artist    48197
23        24   21      F         artist    94533
24        25   39      M       engineer    55107
25        26   49      M       engineer    21044
26        27   40      F      librarian    30030
27        28   32      M         writer    55369
28        29   41      M     programmer    94043
29        30    7      M        student    55436
..       ...  ...    ...            ...      ...
913      914   44      F          other    08105
914      915   50      M  entertainment    60614
915      916   27      M       engineer    N2L5N
916      917   22      F        student    20006
917      918   40      M      scientist    70116
918      919   25      M          other    14216
919      920   30      F         artist    90008
920      921   20      F        student    98801
921      922   29      F  administrator    21114
922      923   21      M        student    E2E3R
923      924   29      M          other    11753
924      925   18      F       salesman    49036
925      926   49      M  entertainment    01701
926      927   23      M     programmer    55428
927      928   21      M        student    55408
928      929   44      M      scientist    53711
929      930   28      F      scientist    07310
930      931   60      M       educator    33556
931      932   58      M       educator    06437
932      933   28      M        student    48105
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [12]:
data.shape[0]

943

In [13]:
data.occupation

0         technician
1              other
2             writer
3         technician
4              other
5          executive
6      administrator
7      administrator
8            student
9             lawyer
10             other
11             other
12          educator
13         scientist
14          educator
15     entertainment
16        programmer
17             other
18         librarian
19         homemaker
20            writer
21            writer
22            artist
23            artist
24          engineer
25          engineer
26         librarian
27            writer
28        programmer
29           student
           ...
913            other
914    entertainment
915         engineer
916          student
917        scientist
918            other
919           artist
920          student
921    administrator
922          student
923            other
924         salesman
925    entertainment
926       programmer
927          student
928        scientist
929        scientist
930         educator
931         educator
932          student
933         engineer
934           doctor
935            other
936         educator
937       technician
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

In [16]:
data.occupation.unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

In [17]:
len(data.occupation.unique())

21

In [19]:
data.occupation.value_counts()

student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
doctor             7
homemaker          7
Name: occupation, dtype: int64

In [20]:
data.age.mean()

34.05196182396607

In [21]:
data.groupby("occupation").mean()

                  user_id        age
occupation
administrator  430.949367  38.746835
artist         451.892857  31.392857
doctor         533.714286  43.571429
educator       466.905263  42.010526
engineer       456.328358  36.388060
entertainment  398.000000  29.222222
executive      422.312500  38.718750
healthcare     501.437500  41.562500
homemaker      443.000000  32.571429
lawyer         359.083333  36.750000
librarian      486.588235  40.000000
marketing      437.807692  37.615385
none           368.666667  26.555556
other          542.733333  34.523810
programmer     435.530303  33.121212
retired        515.714286  63.071429
salesman       494.916667  35.666667
scientist      465.129032  35.548387
student        484.954082  22.081633
technician     497.629630  33.148148
writer         495.711111  36.311111

In [22]:
data.age.min()

7

In [24]:
data[data.age.min()==data.age]

    user_id  age gender occupation zip_code
29       30    7      M    student    55436

In [25]:
data[data.age.max()==data.age]

     user_id  age gender occupation zip_code
480      481   73      M    retired    37771

In [26]:
df = pd.read_csv("https://raw.githubusercontent.com/jokecamp/FootballData/master/UEFA_European_Championship/Euro%202012/Euro%202012%20stats%20TEAM.csv")

In [27]:
df

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [28]:
df.shape

(16, 35)

In [29]:
df.Team.unique()

array(['Croatia', 'Czech Republic', 'Denmark', 'England', 'France',
       'Germany', 'Greece', 'Italy', 'Netherlands', 'Poland', 'Portugal',
       'Republic of Ireland', 'Russia', 'Spain', 'Sweden', 'Ukraine'],
      dtype=object)

In [30]:
df['discipline'] = df['Red Cards'] + df['Yellow Cards']

In [31]:
df

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used,discipline
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,81.3%,41,62,2,9,0,9,9,16,9
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,60.1%,53,73,8,7,0,11,11,19,7
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,66.7%,25,38,8,4,0,7,7,15,4
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,88.1%,43,45,6,5,0,11,11,16,5
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,54.6%,36,51,5,6,0,11,11,19,6
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,62.6%,63,49,12,4,0,15,15,17,4
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,65.1%,67,48,12,9,1,12,12,20,10
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,74.1%,101,89,16,16,0,18,18,19,16
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,70.6%,35,30,3,5,0,7,7,15,5
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,66.7%,48,56,3,7,1,7,7,17,8
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,71.5%,73,90,10,12,0,14,14,16,12
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,65.4%,43,51,11,6,1,10,10,17,7
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,77.0%,34,43,4,6,0,7,7,16,6
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,93.8%,102,83,19,11,0,17,17,18,11
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,61.6%,35,51,7,7,0,9,9,18,7
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,76.5%,48,31,4,5,0,9,9,18,5

In [33]:
df.sort_values(by=['discipline'])

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used,discipline
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,66.7%,25,38,8,4,0,7,7,15,4
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,62.6%,63,49,12,4,0,15,15,17,4
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,88.1%,43,45,6,5,0,11,11,16,5
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,70.6%,35,30,3,5,0,7,7,15,5
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,76.5%,48,31,4,5,0,9,9,18,5
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,54.6%,36,51,5,6,0,11,11,19,6
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,77.0%,34,43,4,6,0,7,7,16,6
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,60.1%,53,73,8,7,0,11,11,19,7
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,65.4%,43,51,11,6,1,10,10,17,7
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,61.6%,35,51,7,7,0,9,9,18,7
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,66.7%,48,56,3,7,1,7,7,17,8
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,81.3%,41,62,2,9,0,9,9,16,9
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,65.1%,67,48,12,9,1,12,12,20,10
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,93.8%,102,83,19,11,0,17,17,18,11
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,71.5%,73,90,10,12,0,14,14,16,12
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,74.1%,101,89,16,16,0,18,18,19,16

In [34]:
df['Yellow Cards'].mean()

7.4375

In [35]:
df.Yellow Cards.mean() # space is the error

SyntaxError: invalid syntax (<ipython-input-35-20ddbe6507a9>, line 1)

In [36]:
df[df.Goals>5]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used,discipline
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,62.6%,63,49,12,4,0,15,15,17,4
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,74.1%,101,89,16,16,0,18,18,19,16
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,71.5%,73,90,10,12,0,14,14,16,12
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,93.8%,102,83,19,11,0,17,17,18,11

In [37]:
df['Shooting Accuracy'].dtype

dtype('O')

In [38]:
df['Shooting Accuracy'].max()

'55.9%'

In [39]:
df

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used,discipline
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,81.3%,41,62,2,9,0,9,9,16,9
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,60.1%,53,73,8,7,0,11,11,19,7
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,66.7%,25,38,8,4,0,7,7,15,4
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,88.1%,43,45,6,5,0,11,11,16,5
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,54.6%,36,51,5,6,0,11,11,19,6
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,62.6%,63,49,12,4,0,15,15,17,4
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,65.1%,67,48,12,9,1,12,12,20,10
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,74.1%,101,89,16,16,0,18,18,19,16
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,70.6%,35,30,3,5,0,7,7,15,5
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,66.7%,48,56,3,7,1,7,7,17,8
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,71.5%,73,90,10,12,0,14,14,16,12
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,65.4%,43,51,11,6,1,10,10,17,7
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,77.0%,34,43,4,6,0,7,7,16,6
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,93.8%,102,83,19,11,0,17,17,18,11
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,61.6%,35,51,7,7,0,9,9,18,7
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,76.5%,48,31,4,5,0,9,9,18,5

In [40]:
df['Fouls Conceded'] > df['Fouls Won']

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9      True
10     True
11     True
12     True
13    False
14     True
15    False
dtype: bool

In [41]:
df[df['Fouls Conceded'] > df['Fouls Won']]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used,discipline
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,81.3%,41,62,2,9,0,9,9,16,9
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,60.1%,53,73,8,7,0,11,11,19,7
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,66.7%,25,38,8,4,0,7,7,15,4
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,88.1%,43,45,6,5,0,11,11,16,5
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,54.6%,36,51,5,6,0,11,11,19,6
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,66.7%,48,56,3,7,1,7,7,17,8
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,71.5%,73,90,10,12,0,14,14,16,12
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,65.4%,43,51,11,6,1,10,10,17,7
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,77.0%,34,43,4,6,0,7,7,16,6
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,61.6%,35,51,7,7,0,9,9,18,7